/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#1a1c19',
        'on-surface-variant': '#404848',
        'tertiary-container': '#434542',
        'primary-fixed': '#b4edec',
        'on-surface': '#1c1b1b',
        'outline-variant': '#bfc8c8',
        'surface-tint': '#2e6767',
        'on-secondary': '#ffffff',
        'surface': '#fcf9f8',
        'on-error-container': '#93000a',
        'secondary-container': '#fe932c',
        'tertiary-fixed-dim': '#c6c7c2',
        'surface-variant': '#e5e2e1',
        'on-primary-fixed-variant': '#104f4f',
        'secondary-fixed-dim': '#ffb77d',
        'primary-fixed-dim': '#98d1d0',
        'surface-container-high': '#eae7e7',
        'surface-bright': '#fcf9f8',
        'on-primary-container': '#85bdbc',
        'secondary-fixed': '#ffdcc3',
        'on-secondary-container': '#663500',
        'on-tertiary': '#ffffff',
        'surface-container-highest': '#e5e2e1',
        'primary': '#003535',
        'on-error': '#ffffff',
        'on-secondary-fixed-variant': '#6e3900',
        'on-background': '#1c1b1b',
        'on-tertiary-container': '#b2b3ae',
        'inverse-surface': '#313030',
        'surface-dim': '#dcd9d9',
        'inverse-on-surface': '#f3f0ef',
        'tertiary': '#2d2f2c',
        'on-tertiary-fixed-variant': '#454744',
        'on-primary-fixed': '#002020',
        'background': '#fcf9f8',
        'outline': '#707978',
        'error': '#ba1a1a',
        'tertiary-fixed': '#e3e3de',
        'secondary': '#904d00',
        'primary-container': '#0d4d4d',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed': '#2f1500',
        'inverse-primary': '#98d1d0',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0eded',
        'on-primary': '#ffffff',
        'error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'gutter-grid': '24px',
        'unit': '4px',
        'padding-card': '32px',
        'stack-gap': '16px',
        'margin-page': '48px',
      },
      fontFamily: {
        'headline-lg': ['Noto Serif', 'serif'],
        'body-md': ['Noto Serif', 'serif'],
        'headline-xl': ['Noto Serif', 'serif'],
        'headline-md': ['Noto Serif', 'serif'],
        'label-md': ['Noto Serif', 'serif'],
        'body-lg': ['Noto Serif', 'serif'],
        serif: ['Noto Serif', 'serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
}
